version: '3'
services:
  pdfbot:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
      lagoon.service.port: 8501
    ports:
      - 8501:8501
    env_file:
      - .env